In [21]:
import pandas as pd
data = pd.read_csv("airline-passengers.csv")

df_target = pd.DataFrame(data, columns=["Passengers"])
df_data = pd.DataFrame(data, columns=["Month"])

sequence = data['Passengers'].values.tolist()
print(sequence)

[112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115, 126, 141, 135, 125, 149, 170, 170, 158, 133, 114, 140, 145, 150, 178, 163, 172, 178, 199, 199, 184, 162, 146, 166, 171, 180, 193, 181, 183, 218, 230, 242, 209, 191, 172, 194, 196, 196, 236, 235, 229, 243, 264, 272, 237, 211, 180, 201, 204, 188, 235, 227, 234, 264, 302, 293, 259, 229, 203, 229, 242, 233, 267, 269, 270, 315, 364, 347, 312, 274, 237, 278, 284, 277, 317, 313, 318, 374, 413, 405, 355, 306, 271, 306, 315, 301, 356, 348, 355, 422, 465, 467, 404, 347, 305, 336, 340, 318, 362, 348, 363, 435, 491, 505, 404, 359, 310, 337, 360, 342, 406, 396, 420, 472, 548, 559, 463, 407, 362, 405, 417, 391, 419, 461, 472, 535, 622, 606, 508, 461, 390, 432]


In [22]:
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence)-1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return X, y
X,y = split_sequence(sequence,4)
print(X)
print(y)


[[112, 118, 132, 129], [118, 132, 129, 121], [132, 129, 121, 135], [129, 121, 135, 148], [121, 135, 148, 148], [135, 148, 148, 136], [148, 148, 136, 119], [148, 136, 119, 104], [136, 119, 104, 118], [119, 104, 118, 115], [104, 118, 115, 126], [118, 115, 126, 141], [115, 126, 141, 135], [126, 141, 135, 125], [141, 135, 125, 149], [135, 125, 149, 170], [125, 149, 170, 170], [149, 170, 170, 158], [170, 170, 158, 133], [170, 158, 133, 114], [158, 133, 114, 140], [133, 114, 140, 145], [114, 140, 145, 150], [140, 145, 150, 178], [145, 150, 178, 163], [150, 178, 163, 172], [178, 163, 172, 178], [163, 172, 178, 199], [172, 178, 199, 199], [178, 199, 199, 184], [199, 199, 184, 162], [199, 184, 162, 146], [184, 162, 146, 166], [162, 146, 166, 171], [146, 166, 171, 180], [166, 171, 180, 193], [171, 180, 193, 181], [180, 193, 181, 183], [193, 181, 183, 218], [181, 183, 218, 230], [183, 218, 230, 242], [218, 230, 242, 209], [230, 242, 209, 191], [242, 209, 191, 172], [209, 191, 172, 194], [191, 172

In [23]:
df = pd.DataFrame(X, columns=['X-3','X-2', 'X-1', 'Xt',])
print (df)

     X-3  X-2  X-1   Xt
0    112  118  132  129
1    118  132  129  121
2    132  129  121  135
3    129  121  135  148
4    121  135  148  148
..   ...  ...  ...  ...
135  461  472  535  622
136  472  535  622  606
137  535  622  606  508
138  622  606  508  461
139  606  508  461  390

[140 rows x 4 columns]


In [24]:
from sklearn.preprocessing import MinMaxScaler
import joblib

scaler = MinMaxScaler()
#scaler.fit(features)
#scaler.transform(features)
scaled = scaler.fit_transform(df)
features_names = df.columns.copy()
#features_names.remove('label')
scaled_features = pd.DataFrame(scaled, columns=features_names)
scaled_features

X-3       X-2       X-1        Xt
0    0.015444  0.027027  0.054054  0.048263
1    0.027027  0.054054  0.048263  0.032819
2    0.054054  0.048263  0.032819  0.059846
3    0.048263  0.032819  0.059846  0.084942
4    0.032819  0.059846  0.084942  0.084942
..        ...       ...       ...       ...
135  0.689189  0.710425  0.832046  1.000000
136  0.710425  0.832046  1.000000  0.969112
137  0.832046  1.000000  0.969112  0.779923
138  1.000000  0.969112  0.779923  0.689189
139  0.969112  0.779923  0.689189  0.552124

[140 rows x 4 columns]

In [25]:
dataX = scaled_features.drop(columns=['Xt'])
dataX

X-3       X-2       X-1
0    0.015444  0.027027  0.054054
1    0.027027  0.054054  0.048263
2    0.054054  0.048263  0.032819
3    0.048263  0.032819  0.059846
4    0.032819  0.059846  0.084942
..        ...       ...       ...
135  0.689189  0.710425  0.832046
136  0.710425  0.832046  1.000000
137  0.832046  1.000000  0.969112
138  1.000000  0.969112  0.779923
139  0.969112  0.779923  0.689189

[140 rows x 3 columns]

In [26]:
dataY = scaled_features['Xt'].values
dataY

array([0.04826255, 0.03281853, 0.05984556, 0.08494208, 0.08494208,
       0.06177606, 0.02895753, 0.        , 0.02702703, 0.02123552,
       0.04247104, 0.07142857, 0.05984556, 0.04054054, 0.08687259,
       0.12741313, 0.12741313, 0.1042471 , 0.05598456, 0.01930502,
       0.06949807, 0.07915058, 0.08880309, 0.14285714, 0.11389961,
       0.13127413, 0.14285714, 0.18339768, 0.18339768, 0.15444015,
       0.11196911, 0.08108108, 0.11969112, 0.12934363, 0.14671815,
       0.17181467, 0.14864865, 0.15250965, 0.22007722, 0.24324324,
       0.26640927, 0.2027027 , 0.16795367, 0.13127413, 0.17374517,
       0.17760618, 0.17760618, 0.25482625, 0.25289575, 0.24131274,
       0.26833977, 0.30888031, 0.32432432, 0.25675676, 0.20656371,
       0.14671815, 0.18725869, 0.19305019, 0.16216216, 0.25289575,
       0.23745174, 0.25096525, 0.30888031, 0.38223938, 0.36486486,
       0.2992278 , 0.24131274, 0.19111969, 0.24131274, 0.26640927,
       0.24903475, 0.31467181, 0.31853282, 0.32046332, 0.40733

In [29]:
from sklearn.model_selection import train_test_split
training, test = train_test_split(dataX,test_size=0.8, random_state=1)#Nilai X training dan Nilai X testing
training_label, test_label = train_test_split(dataY, test_size=0.8, random_state=1)#Nilai Y training dan Nilai Y testing

In [32]:
from numpy import array
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
# find the end of this pattern
        end_ix = i + n_steps
# check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
# gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)

    return array(X), array(y)
# define univariate time series
print(series.shape)
# transform to a supervised learning problem
X, y = split_sequence(test_label, 4)
print(X.shape, y.shape)
# show each sample
for i in range(len(X)):
    print(X[i], y[i])


(10,)
(108, 4) (108,)
[0.2992278  0.16216216 0.16795367 0.41312741] 0.06177606177606179
[0.16216216 0.16795367 0.41312741 0.06177606] 0.41119691119691115
[0.16795367 0.41312741 0.06177606 0.41119691] 0.15444015444015444
[0.41312741 0.06177606 0.41119691 0.15444015] 0.019305019305019294
[0.06177606 0.41119691 0.15444015 0.01930502] 0.25289575289575295
[0.41119691 0.15444015 0.01930502 0.25289575] 0.3204633204633204
[0.15444015 0.01930502 0.25289575 0.32046332] 0.3281853281853282
[0.01930502 0.25289575 0.32046332 0.32818533] 0.08687258687258684
[0.25289575 0.32046332 0.32818533 0.08687259] 0.38803088803088803
[0.32046332 0.32818533 0.08687259 0.38803089] 0.3088803088803088
[0.32818533 0.08687259 0.38803089 0.30888031] 0.1776061776061776
[0.08687259 0.38803089 0.30888031 0.17760618] 0.5540540540540541
[0.38803089 0.30888031 0.17760618 0.55405405] 0.4015444015444015
[0.30888031 0.17760618 0.55405405 0.4015444 ] 0.20656370656370657
[0.17760618 0.55405405 0.4015444  0.20656371] 0.14864864864

predikisi-aktual/prediksi
x100%