In [1]:
!pip install pandas
!pip install numpy
!pip install scikit-learn

In [2]:
import pandas as pd
data = pd.read_csv('airline-passengers.csv')
data

Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]

In [3]:
import numpy as np

In [4]:
training_set = data.iloc[:115, 1:2].values
test_set = data.iloc[115:, 1:2].values

In [5]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)
# Creating a data structure with 60 time-steps and 1 output
X_train = []
y_train = []
x = 4
for i in range(x, 115):
    X_train.append(training_set_scaled[i-x:i, 0])
    y_train.append(training_set_scaled[i, 0])
X_train, y_train = np.array(X_train), np.array(y_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

print(X_train)

[[[0.02067183]
  [0.03617571]
  [0.07235142]
  [0.06459948]]

 [[0.03617571]
  [0.07235142]
  [0.06459948]
  [0.04392765]]

 [[0.07235142]
  [0.06459948]
  [0.04392765]
  [0.08010336]]

 [[0.06459948]
  [0.04392765]
  [0.08010336]
  [0.11369509]]

 [[0.04392765]
  [0.08010336]
  [0.11369509]
  [0.11369509]]

 [[0.08010336]
  [0.11369509]
  [0.11369509]
  [0.08268734]]

 [[0.11369509]
  [0.11369509]
  [0.08268734]
  [0.03875969]]

 [[0.11369509]
  [0.08268734]
  [0.03875969]
  [0.        ]]

 [[0.08268734]
  [0.03875969]
  [0.        ]
  [0.03617571]]

 [[0.03875969]
  [0.        ]
  [0.03617571]
  [0.02842377]]

 [[0.        ]
  [0.03617571]
  [0.02842377]
  [0.05684755]]

 [[0.03617571]
  [0.02842377]
  [0.05684755]
  [0.09560724]]

 [[0.02842377]
  [0.05684755]
  [0.09560724]
  [0.08010336]]

 [[0.05684755]
  [0.09560724]
  [0.08010336]
  [0.05426357]]

 [[0.09560724]
  [0.08010336]
  [0.05426357]
  [0.11627907]]

 [[0.08010336]
  [0.05426357]
  [0.11627907]
  [0.17054264]]

 [[0.054

In [7]:
xtrainbaru = np.reshape(X_train, (45, 5))

ValueError: cannot reshape array of size 444 into shape (45,5)